steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/solid-photon-196602/myxcc', '.']
images: ['asia-southeast1-docker.pkg.dev/solid-photon-196602/myxcc']
