FROM openjdk:19-jdk-alpine

MAINTAINER  mycc


WORKDIR /data
ARG JAR_FILE=JAR_FILE_MUST_BE_SPECIFIED_AS_BUILD_ARG
COPY ${JAR_FILE} /data/app.jar

ENV JAVA_OPTS=""
ENTRYPOINT exec java $JAVA_OPTS -jar app.jar
